const { join } = require('node:path');

/**
 * For a detailed explanation regarding each configuration property and type check, visit:
 * https://jestjs.io/docs/configuration
 * @type {import('jest').Config}
 */
module.exports = {
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['node_modules', '<rootDir>/src/typechain-types'], // Coverage is collected for all files imported by the tests. We want to exclude files generated by Typechain.
  coverageProvider: 'v8',

  preset: 'ts-jest',
  resetMocks: true,
  restoreMocks: true,
  setupFiles: [join(__dirname, './jest.setup.js')],
  testEnvironment: 'jest-environment-node',
  testMatch: ['**/?(*.)+(spec|test).[t]s?(x)'],
  testPathIgnorePatterns: ['<rootDir>/.build', '<rootDir>/dist/', '<rootDir>/build/'],
  verbose: true,
};
