name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-build-test:
    runs-on: ubuntu-latest
    name: Build, lint and test
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Lint Typescript
        run: pnpm run tsc
      - name: Lint
        run: pnpm run prettier:check && pnpm run eslint:check
      - name: Test
        run: pnpm run test --bail

  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Start Hardhat
        run: pnpm dev:eth-node&
      - name: Test E2E
        run: pnpm test:e2e --bail

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [documentation, lint-build-test, test-e2e]
    steps:
      - run: exit 0
